package com.paypay.baymax.domain.security;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.paypay.baymax.domain.general.TAudit;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", uniqueConstraints = { @UniqueConstraint(name = "olivo", columnNames = "group_name") })
@JsonSerialize(include = JsonSerialize.Inclusion.NON_EMPTY)
@Audited(targetAuditMode = org.hibernate.envers.RelationTargetAuditMode.NOT_AUDITED)
public class Groups extends TAudit implements java.io.Serializable {

	private static final long serialVersionUID = 4900736961147058007L;
	private long id;
	private String group_name;
	private String description;
	private String assignedAuthorities;
	private Set<Group_members> groupMemberses = new HashSet<Group_members>(0);
	
	public Groups() {
	}

	/**
	 * 
	 * @param id         Identificador del grupo
	 * @param group_name Nombre del grupo
	 */
	public Groups(long id, String group_name) {
		this.id = id;
		this.group_name = group_name;
	}

	/**
	 * 
	 * @param id
	 * @param group_name
	 * @param description
	 */
	public Groups(long id, String group_name, String description) {
		super();
		this.id = id;
		this.group_name = group_name;
		this.description = description;
	}

	/**
	 * 
	 * @param id
	 * @param group_name
	 * @param groupMemberses
	 */
	public Groups(long id, String group_name, Set<Group_members> groupMemberses) {
		this.id = id;
		this.group_name = group_name;
		this.groupMemberses = groupMemberses;
	}

	// Beans ...........................................

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "group_name", nullable = false, length = 50)
	public String getGroup_name() {
		return this.group_name;
	}

	public void setGroup_name(String group_name) {
		this.group_name = group_name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "assignedAuthorities", columnDefinition = "text")
	public String getAssignedAuthorities() {
		return assignedAuthorities;
	}

	public void setAssignedAuthorities(String assignedAuthorities) {
		this.assignedAuthorities = assignedAuthorities;
	}

	@JsonIgnore
	@NotAudited
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "group_id")
	public Set<Group_members> getGroupMemberses() {
		return this.groupMemberses;
	}

	public void setGroupMemberses(Set<Group_members> groupMemberses) {
		this.groupMemberses = groupMemberses;
	}

}
